# App container which provides the php environment
app:
  # For development of the image comment out the 'image' line and replace with the next line
  #build: .
  image: visay/dockertypo3:7.6.2
  volumes_from:
    - data
  volumes:
    - ./config/web/ip_address.txt:/ip_address.txt:ro
    - ./scripts/entrypoint/app.sh:/entrypoint.sh:ro
  expose:
    - "9000"
  links:
    - db
    - mail
    - redis
    - elasticsearch
    - couchdb
  environment:
    - HOST_USER_ID

# Passive data container which only provides a shared filesystem for the other containers
data:
  image: mariadb:10.0
  command: echo "Data container has started"
  volumes:
    - ../../..:/var/www
    - /var/lib/mysql

db:
  image: mariadb:10.0
  volumes_from:
    - data
  volumes:
    - ./scripts/entrypoint/db.sh:/entrypoint.sh:ro
  ports:
    - "3307:3306"
  entrypoint: /entrypoint.sh
  command: mysqld --user=root
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: dockertypo3 dockertypo3_test

web:
  image: nginx:1.7
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./config/web/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./config/web/.nginx_default_merged.conf:/etc/nginx/default/vhost.conf:ro
    - ./config/web/.nginx_default_test_merged.conf:/etc/nginx/default/vhost_test.conf:ro
    - ./config/web/nginx_ssl.conf:/etc/nginx/default/vhost_ssl.conf:ro
    - ./config/web/nginx_vhost_default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./config/web/nginx_vhost_ssl.conf:/etc/nginx/conf.d/default_ssl.conf:ro
    - ./config/web/ssl/dockertypo3.crt:/etc/ssl/certs/dockertypo3.crt:ro
    - ./config/web/ssl/dockertypo3.key:/etc/ssl/private/dockertypo3.key:ro
    - ./config/web/ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem:ro
    - ./config/web/ip_address.txt:/ip_address.txt:rw
    - ./scripts/entrypoint/web.sh:/entrypoint.sh:ro
  volumes_from:
    - data
  links:
    - app

mail:
  image: mailhog/mailhog:latest
  ports:
    - "8025:8025"

redis:
  image: redis:3.0
  ports:
    - "6379:6379"

elasticsearch:
  image: elasticsearch:1.4
  ports:
    - "9200:9200"
  volumes:
    - ./config/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

couchdb:
  image: klaemo/couchdb:1.6
  ports:
    - "5984:5984"
